# Generated by Django 4.2.5 on 2023-11-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelApp.estado'),
        ),
    ]
